name: Send Daily Reading Notification
on:
  schedule:
    - cron: '30 2 * * *' # Runs every day at 08:00 AM IST (UTC 2:30)
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  send-notif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install firebase-admin
      - run: node scripts/fcm_daily_readings.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}